name: ${project.name}
main: net.opmasterleo.combat.Combat
version: ${project.version}
api-version: 1.21
author: OPmasterLEO
description: ${project.description}
folia-supported: true
softdepend:
  - WorldGuard
  - PacketEvents
  - PlaceholderAPI
  - SuperVanish
  - PremiumVanish
commands:
  combat:
    description: Main command for combat plugin.
    usage: /combat <toggle|reload|visibility|update>
    permission: combat.admin
    permission-message: You do not have permission to use this command.
  protection:
    description: Check your PvP protection time left.
    usage: /protection
    permission: combat.protection
    permission-message: You do not have permission to use this command.
  ${settings.disableCommand}:
    description: Disable your newbie PvP protection.
    usage: /${settings.disableCommand}
    permission: combat.protection
    permission-message: You do not have permission to use this command.
permissions:
  combat.admin:
    description: Access to all combat admin commands
    default: op
  combat.protection:
    description: Access to protection commands
    default: true
  combat.bypass.safezone:
    description: Allows bypassing safezone barriers during combat
    default: op